 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.millivendas.telas;
import java.sql.*;
import br.com.millivendas.dal.Modulo_conector;
import javax.swing.JOptionPane;

/**
 *
 * @author Danilo
 */
public class NovoCadastro extends javax.swing.JFrame {
  /*  Connection conexao = null;
    PreparedStatement PST= null;
    
   
    public void newCad(){
        
        String SQL = "insert into register_of_users (name_user, phone_number,email_user, login_user, password_user, profile_user"+
        "values(?,?,?,?,?)";
        try {
            
            PST = conexao.prepareStatement(SQL);
            PST.setString(1, txtNome.getText());
            PST.setString(2, txtTelefone.getText());
            
            PST.setString(3,txtEmail.getText());
            PST.setString(4,txtConfirmeEmail.getText());
      
            if(txtEmail == txtConfirmeEmail){
                String caption = new String(passSenha.getPassword());
                String confirmCaption = new String(passConfirmSenha.getPassword());
                
                if(caption == confirmCaption){     
                    
                    PST.setString(5, caption);
                    TelaPrincipal T2principal = new TelaPrincipal();
                    PST.execute();
                    T2principal.setVisible(true);
                    PST.close();
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Senhas incopativeis !");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Emails INCOPATIVEIS !");
            } 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
 */   
    public NovoCadastro() {
        initComponents();

      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCad = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtConfirmeEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passConfirmSenha = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblExibiSenha = new javax.swing.JLabel();
        passSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Preencha os campos abaixo para completar seu cadastro:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 53, -1, 28));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("CADASTRO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 19, -1, 28));

        btnCad.setBackground(new java.awt.Color(106, 146, 255));
        btnCad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCad.setForeground(new java.awt.Color(255, 255, 255));
        btnCad.setText("CONFIRMAR");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });
        getContentPane().add(btnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 210, -1));

        jLabel4.setText("* Nome:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 164, 51, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 186, 378, -1));

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("* Campos OBRIGATÓRIOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 123, 150, -1));

        jLabel6.setText("* Telefone: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 226, -1, -1));
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 254, 378, -1));

        jLabel7.setText("* Email :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 322, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 340, 378, -1));

        jLabel9.setText("* Confirme seu email :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 374, -1, -1));
        getContentPane().add(txtConfirmeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 396, 378, -1));

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("ATENÇÃO !  esse será seu login de usuário");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 322, 249, -1));
        getContentPane().add(passConfirmSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 531, 378, -1));

        jLabel8.setText("* Senha:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 447, -1, -1));

        jLabel10.setText("* Confirme sua senha:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 509, -1, -1));

        lblExibiSenha.setForeground(new java.awt.Color(102, 102, 102));
        lblExibiSenha.setText("Digite sua senha");
        getContentPane().add(lblExibiSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 466, 100, 30));
        getContentPane().add(passSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 469, 378, -1));

        setSize(new java.awt.Dimension(477, 676));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed

     
       
    }//GEN-LAST:event_btnCadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblExibiSenha;
    private javax.swing.JPasswordField passConfirmSenha;
    private javax.swing.JPasswordField passSenha;
    private javax.swing.JTextField txtConfirmeEmail;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
