/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.projetoacademico.telasgraficas;

import br.com.projetoacademico.dao.DaoProfessor;
import br.com.projetoacademico.projetoescola.Cursos;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Danilo
 */
public class TelaCadastroCursos extends javax.swing.JInternalFrame {

    private final DaoProfessor updateInformations;
    private final HashMap<String, Cursos> cursos = new HashMap();
    private Cursos newCurso;

    /**
     * Creates new form TelaCadastroCursos
     *
     * @param updateInformations
     */
    public TelaCadastroCursos(DaoProfessor updateInformations) {
        this.updateInformations = updateInformations;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        comboCurso = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCadDisciplinas = new javax.swing.JTextArea();
        btnCadDisciplinas = new javax.swing.JButton();
        btnCadastrarCurso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setMaximumSize(new java.awt.Dimension(600, 550));
        setMinimumSize(new java.awt.Dimension(600, 550));
        setPreferredSize(new java.awt.Dimension(600, 550));

        jLabel11.setText("<html>  <p>ATENÇÃO, No campo de disciplinas<br> \nInforme um abaixo do outro, todas as disciplinas que o professor terá. <br> \nCaso deseje cadastrar só o curso ou só as disciplinas, clique no botão<br>\ncorrespondente ao que deseja.\n</p> </html>");

        comboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha um curso", "ADS", "AGR ", "LOG ", " " }));

        jLabel12.setText("Curso:");

        jLabel13.setText("Disciplinas");

        txtCadDisciplinas.setColumns(20);
        txtCadDisciplinas.setRows(5);
        jScrollPane2.setViewportView(txtCadDisciplinas);

        btnCadDisciplinas.setText("Cadastrar nova disciplina");
        btnCadDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDisciplinasActionPerformed(evt);
            }
        });

        btnCadastrarCurso.setText("Cadastrar novo curso");
        btnCadastrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCursoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("Cadastrar Cursos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastrarCurso)
                                .addGap(61, 61, 61)
                                .addComponent(btnCadDisciplinas))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarCurso)
                    .addComponent(btnCadDisciplinas))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDisciplinasActionPerformed
        adicionarDisciplinas();
    }//GEN-LAST:event_btnCadDisciplinasActionPerformed

    private void btnCadastrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCursoActionPerformed
        adicionarNovosCursos();

    }//GEN-LAST:event_btnCadastrarCursoActionPerformed
    public void adicionarNovosCursos() {
        String confirmRegistro = JOptionPane.showInputDialog(null, "Primeiramente, informe o registro do professor que deseja adicionas o curso: ", "Cadastro de cursos", JOptionPane.OK_CANCEL_OPTION);
        int confirmOption;
        int registroChecked;
        String nameCourse = comboCurso.getSelectedItem().toString();
        if (nameCourse.equals("Escolha um curso")) {
            JOptionPane.showMessageDialog(null, "É necessario informar o curso para continuar !");
        } else {
            if (confirmRegistro != null) {
                if (confirmRegistro.matches("[0-9]+")) {
                    registroChecked = Integer.parseInt(confirmRegistro.toString());
                    if (updateInformations.pesquisarProfessor(registroChecked) != null) {
                        confirmOption = JOptionPane.showConfirmDialog(null, "Professor encontrado: " + updateInformations.pesquisarProfessor(registroChecked).getName()
                                + ". Caso deseje continuar clique em ok", "Search Professor", JOptionPane.OK_CANCEL_OPTION);
                        if (confirmOption == JOptionPane.OK_OPTION) {
                            newCurso = new Cursos(comboCurso.getSelectedItem().toString());
                            cursos.put(nameCourse, newCurso);
                            updateInformations.pesquisarProfessor(registroChecked).setCursos(cursos);
                            JOptionPane.showMessageDialog(null, "Curso cadastrado com sucesso !");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Professor não encontrado !");
                }
            }
        }
    }

    public void adicionarDisciplinas() {
        String confirmRegister = JOptionPane.showInputDialog(null, "Informe o registro do professor:");
        String searchCourse;
        int registerChecked;

        ArrayList<String> disciplinas = new ArrayList();
        if (confirmRegister != null) {
            registerChecked = Integer.parseInt((confirmRegister.toString()));
            if (updateInformations.pesquisarProfessor(registerChecked) != null) {
                searchCourse = JOptionPane.showInputDialog(null, "Informe o nome do curso que deseja adicionar a disciplina");
                if (searchCourse != null) {
                    if (txtCadDisciplinas.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "ATENÇÃO !\nÉ necessario informar as disciplinas no campo de texto abaixo de cursos !");
                    } else {
                        disciplinas.add(txtCadDisciplinas.getText().toString());
                        updateInformations.cadastrarDisciplinas(searchCourse.toUpperCase(), disciplinas, registerChecked);
                        JOptionPane.showMessageDialog(null, "Disciplinas cadastradas com sucesso !");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Professor não encontrado !");
            }

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadDisciplinas;
    private javax.swing.JButton btnCadastrarCurso;
    private javax.swing.JComboBox<String> comboCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCadDisciplinas;
    // End of variables declaration//GEN-END:variables
}
