/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projetoacademico.telasgraficas;

import br.com.projetoacademico.telasgraficas.professor.*;
import br.com.projetoacademico.dao.DaoAluno;
import br.com.projetoacademico.dao.DaoProfessor;
import br.com.projetoacademico.telasgraficas.cursos.TelaCadastroCursos;
import br.com.projetoacademico.telasgraficas.alunos.*;
import br.com.projetoacademico.telasgraficas.cursos.TelaAlterarCursos;
import javax.swing.JOptionPane;

/**
 *
 * @author Danilo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    DaoAluno daoAluno;
    DaoProfessor daoProfessor;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        daoAluno = new DaoAluno();
        daoProfessor = new DaoProfessor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuAluno = new javax.swing.JMenu();
        cadAluno = new javax.swing.JMenuItem();
        menuExcluir = new javax.swing.JMenuItem();
        menuAlterarAluno = new javax.swing.JMenuItem();
        menuPesquisar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuCadProf = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuSearhProf = new javax.swing.JMenuItem();
        jalterarProfessor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Acadêmico");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        desktopPrincipal.setMaximumSize(new java.awt.Dimension(600, 550));
        desktopPrincipal.setMinimumSize(new java.awt.Dimension(600, 550));

        javax.swing.GroupLayout desktopPrincipalLayout = new javax.swing.GroupLayout(desktopPrincipal);
        desktopPrincipal.setLayout(desktopPrincipalLayout);
        desktopPrincipalLayout.setHorizontalGroup(
            desktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        desktopPrincipalLayout.setVerticalGroup(
            desktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Sistema Acadêmico");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Bem vindo !");

        jLabel3.setText("<html> \t<p> \tTodas as opções referente aos alunos e <br> \tprofessores, podem ser encontradas <br> \tno canto superior esquerdo.  \t</p> </html>");

        jmenuAluno.setText("Area Aluno");
        jmenuAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuAlunoActionPerformed(evt);
            }
        });

        cadAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cadAluno.setText("Cadastrar novo aluno");
        cadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAlunoActionPerformed(evt);
            }
        });
        jmenuAluno.add(cadAluno);

        menuExcluir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuExcluir.setText("Excluir aluno");
        menuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirActionPerformed(evt);
            }
        });
        jmenuAluno.add(menuExcluir);

        menuAlterarAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuAlterarAluno.setText("Alterar informações do aluno");
        menuAlterarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarAlunoActionPerformed(evt);
            }
        });
        jmenuAluno.add(menuAlterarAluno);

        menuPesquisar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPesquisar.setText("Pesquisar aluno");
        menuPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisarActionPerformed(evt);
            }
        });
        jmenuAluno.add(menuPesquisar);

        jMenuBar1.add(jmenuAluno);

        jMenu1.setText("Area Professor");

        menuCadProf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuCadProf.setText("Cadastrar professor");
        menuCadProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProfActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadProf);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Excluir professor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menuSearhProf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSearhProf.setText("Pesquisar professor");
        menuSearhProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSearhProfActionPerformed(evt);
            }
        });
        jMenu1.add(menuSearhProf);

        jalterarProfessor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jalterarProfessor.setText("Alterar dados do professor");
        jalterarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jalterarProfessorActionPerformed(evt);
            }
        });
        jMenu1.add(jalterarProfessor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Area Cursos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Cadastrar cursos e disciplinas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("Alterar Cursos e/ou disciplinas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Opções");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Sobre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(115, 115, 115))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(111, 111, 111)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
            .addComponent(desktopPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAlunoActionPerformed
        TelaCadastroAluno telaCad1 = new TelaCadastroAluno(this.daoAluno);
        telaCad1.setVisible(true);
        desktopPrincipal.add(telaCad1);
    }//GEN-LAST:event_cadAlunoActionPerformed

    private void menuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirActionPerformed
        TelaExcluirAluno telaExcluir = new TelaExcluirAluno(this.daoAluno);
        telaExcluir.setVisible(true);
        desktopPrincipal.add(telaExcluir);
    }//GEN-LAST:event_menuExcluirActionPerformed

    private void menuSearhProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSearhProfActionPerformed
        TelaPesquisarProfessores telaPesquisarProfessor = new TelaPesquisarProfessores(daoProfessor);
        telaPesquisarProfessor.setVisible(true);
        desktopPrincipal.add(telaPesquisarProfessor);
    }//GEN-LAST:event_menuSearhProfActionPerformed

    private void menuCadProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProfActionPerformed

        TelaCadastroProfessor telaCadprof = new TelaCadastroProfessor(daoProfessor);
        telaCadprof.setVisible(true);
        desktopPrincipal.add(telaCadprof);
    }//GEN-LAST:event_menuCadProfActionPerformed

    private void menuPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisarActionPerformed
        TelaPesquisarAluno searchAluno = new TelaPesquisarAluno(this.daoAluno);
        searchAluno.setVisible(true);
        desktopPrincipal.add(searchAluno);
    }//GEN-LAST:event_menuPesquisarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaExcluirProfessor telaExcluirProf = new TelaExcluirProfessor(daoProfessor);
        telaExcluirProf.setVisible(true);
        desktopPrincipal.add(telaExcluirProf);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuAlterarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarAlunoActionPerformed
        TelaAlterarAluno alterarAluno = new TelaAlterarAluno(daoAluno);
        alterarAluno.setVisible(true);
        desktopPrincipal.add(alterarAluno);
    }//GEN-LAST:event_menuAlterarAlunoActionPerformed

    private void jmenuAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuAlunoActionPerformed

    }//GEN-LAST:event_jmenuAlunoActionPerformed

    private void jalterarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jalterarProfessorActionPerformed
        TelaAlterarProfessor alterarProfessor = new TelaAlterarProfessor(daoProfessor);
        alterarProfessor.setVisible(true);
        desktopPrincipal.add(alterarProfessor);
        
    }//GEN-LAST:event_jalterarProfessorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaCadastroCursos cadastrarCurso = new TelaCadastroCursos(daoProfessor);
        cadastrarCurso.setVisible(true);
        desktopPrincipal.add(cadastrarCurso);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
       
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         JOptionPane.showMessageDialog(null, "Desenvolvido por: Danilo de Araújo Leite Gomes. \nO software foi desenvolvido a fim de estudo, quaisquer erros que ocorram\ninforme o desenvolvedor responsavel.","Informações adicionais",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaAlterarCursos alterCourses = new TelaAlterarCursos(daoProfessor);
        alterCourses.setVisible(true);
        desktopPrincipal.add(alterCourses);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem cadAluno;
    public static javax.swing.JDesktopPane desktopPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    public static javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jalterarProfessor;
    public static javax.swing.JMenu jmenuAluno;
    private javax.swing.JMenuItem menuAlterarAluno;
    public static javax.swing.JMenuItem menuCadProf;
    private javax.swing.JMenuItem menuExcluir;
    private javax.swing.JMenuItem menuPesquisar;
    private javax.swing.JMenuItem menuSearhProf;
    // End of variables declaration//GEN-END:variables
}
